version: "3"

services:
  fdk-rdf-parser-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-rdf-parser-service:test
    build: .
    ports:
      - 8080:8080
    environment:
      - LOG_LEVEL=DEBUG
      - API_KEY=test-key
      - HOST_PORT=8080
