version: '3'

services:
  fdk-rdf-parser-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-rdf-parser-service:test
    build: .
    environment:
      - RABBIT_HOST=rabbitmq
      - CONFIG=production
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
