version: "3"

services:
  fdk-rdf-parser-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-rdf-parser-service:test
    build: .
    init: true
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - REASONING_URL=http://fdk-services-mock:8080
      - REFERENCE_DATA_URL=http://fdk-services-mock:8080
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      fdk-services-mock:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  fdk-services-mock:
    image: rodolpheche/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mock/mappings:/home/wiremock/mappings
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://fdk-services-mock:8080/__admin/mappings"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 3s
