version: "3"

services:
  fdk-rdf-parser-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-rdf-parser-service:test
    build: .
    init: true
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
