version: "3"

services:
  fdk-rdf-parser-service:
    image: ghcr.io/informasjonsforvaltning/fdk-rdf-parser-service:staging_latest
    build: .
    ports:
      - 8080:8080
    environment:
      - LOG_LEVEL=DEBUG
      - API_KEY=test-key
