[tool.poetry]
name = "fdk-rdf-parser-service"
version = "0.1.0"
description = "A Python service that parses RDF data to JSON and serves it to frontend applications."
authors = ["Digdir <fellesdatakatalog@digdir.no>"]
homepage = "https://github.com/Informasjonsforvaltning/fdk-rdf-parser-service"
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
rdflib = "^6.3.2"
isodate = "^0.6.1"
python-json-logger = "^2.0.7"
pydantic = "^1.10.7"
aio-pika = "^9.0.5"
aiohttp = "^3.8.4"
python-dotenv = "^0.21.1"
aiohttp-middlewares = "^2.2.0"
fdk-rdf-parser = "2.2.11"

[tool.poetry.group.dev.dependencies]
aiohttp-devtools = "^1.0.post0"
black = "^22.8.0"
codecov = "^2.1.13"
coverage = {extras = ["toml"], version = "^6.4.4"}
flake8 = "^6.0.0"
flake8-annotations = "^2.9.1"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.6"
flake8-builtins = "^2.1.0"
flake8-bugbear = "^23.2.13"
flake8-docstrings = "^1.7.0"
flake8-import-order = "^0.18.2"
flake8-isort = "^6.0.0"
flake8-rst-docstrings = "^0.3.0"
mypy = "^1.2.0"
nox = "^2022.11.21"
nox-poetry = "^1.0.2"
pep8-naming = "^0.13.3"
pytest = "^7.2.1"
pytest-aiohttp = "^1.0.4"
pytest-asyncio = "^0.20.3"
pytest-cov = "^3.0.0"
pytest-docker = "^1.0.1"
pytest-mock = "^3.10.0"
PyYAML = "^5.4"
requests = "^2.31.0"
safety = "^2.3.5"
types-requests = "^2.28.11.12"


[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "pythonjsonlogger.*",
  "nox",
  "nox_poetry.*",
  "requests.*",
  "pytest_mock.*",
  "isodate",
  "rdflib",
]

[[tool.mypy.overrides]]
follow_imports = "skip"
module = "rdflib.*"

[tool.coverage.run]
source = ["fdk_rdf_parser_service"]

[tool.coverage.report]
fail_under = 0

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
  "unit: marks tests as unit (fast)",
  "integration: marks tests as integration (slower)",
  "contract: marks test as contract (slow)",
]

[tool.isort]
extend_skip_glob = [".*"]
profile = "black"
line_length=120
multi_line_output=3

# from 'google' profile
force_sort_within_sections=true
lexicographical=true
order_by_type=false
group_by_package=true

src_paths = ["fdk_rdf_parser_service", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
