---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-rdf-parser-service
  labels:
    app: fdk-rdf-parser-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-rdf-parser-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-rdf-parser-service
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: fdk-rdf-parser-service
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-rdf-parser-service
                  key: API_KEY
          image: fdk-rdf-parser-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 750Mi
              cpu: 500m
            limits:
              memory: 750Mi
