name: Coverage
permissions:
  contents: read
  packages: write
on: push
jobs:
  coverage:
    name: Coverage
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-nox.yaml@main
    with:
      python_version: "3.13"
      python_architecture: x64
      sessions: tests
      coverage_file_path: "./coverage.xml"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
